CREATE TABLE SECUREUSERDATA_COL_PERMISS
(
  ID           VARCHAR2(32 CHAR)                NOT NULL,
  COLSET       VARCHAR2(32 CHAR)                NOT NULL,
  SCHEMA_NAME  VARCHAR2(32 CHAR)                NOT NULL,
  ACTION       VARCHAR2(32 CHAR)                NOT NULL
);

COMMENT ON TABLE SECUREUSERDATA_COL_PERMISS IS 'holds column permissions per schema';

COMMENT ON COLUMN SECUREUSERDATA_COL_PERMISS.ID IS 'uuid';

COMMENT ON COLUMN SECUREUSERDATA_COL_PERMISS.COLSET IS 'predefined column sets, e.g. all, name, contact, ids';

COMMENT ON COLUMN SECUREUSERDATA_COL_PERMISS.SCHEMA_NAME IS 'the schema name in all caps';

COMMENT ON COLUMN SECUREUSERDATA_COL_PERMISS.ACTION IS 'read or write';



CREATE UNIQUE INDEX SECUREUSERDATA_COL_PERMISS_PK ON SECUREUSERDATA_COL_PERMISS
(ID);


CREATE INDEX SUD_COL_PERMISS_SCHEMA_IDX ON SECUREUSERDATA_COL_PERMISS
(SCHEMA_NAME);


ALTER TABLE SECUREUSERDATA_COL_PERMISS ADD (
  CONSTRAINT SECUREUSERDATA_COL_PERMISS_PK
  PRIMARY KEY
  (ID)
  USING INDEX SECUREUSERDATA_COL_PERMISS_PK);

GRANT SELECT ON SECUREUSERDATA_COL_PERMISS TO FASTDEV2;

GRANT SELECT ON SECUREUSERDATA_COL_PERMISS TO FASTDEV3;
