package edu.internet2.middleware.grouper.userLifecycle;

import org.apache.commons.lang3.builder.EqualsBuilder;

import edu.internet2.middleware.grouper.tableIndex.TableIndex;
import edu.internet2.middleware.grouper.tableIndex.TableIndexType;
import edu.internet2.middleware.grouperClient.jdbc.GcDbAccess;
import edu.internet2.middleware.grouperClient.jdbc.GcDbVersionable;
import edu.internet2.middleware.grouperClient.jdbc.GcPersist;
import edu.internet2.middleware.grouperClient.jdbc.GcPersistableClass;
import edu.internet2.middleware.grouperClient.jdbc.GcPersistableField;
import edu.internet2.middleware.grouperClient.jdbc.GcPersistableHelper;
import edu.internet2.middleware.grouperClient.jdbc.GcSqlAssignPrimaryKey;
import edu.internet2.middleware.grouperClient.util.GrouperClientUtils;

@GcPersistableClass(tableName="grouper_lifecycle_event", defaultFieldPersist=GcPersist.doPersist)
public class GrouperLifecycleEvent implements GcSqlAssignPrimaryKey, GcDbVersionable {

  @GcPersistableField(primaryKey=true, primaryKeyManuallyAssigned=true)
  private long internalId = -1;

  @GcPersistableField(columnName = "grpr_lcycl_evnt_cnfg_intrnl_id")
  private Long groupLifecycleEventConfigInternalId;

  @GcPersistableField(columnName = "member_internal_id")
  private Long memberInternalId;
  
  @GcPersistableField(columnName = "event_micros")
  private Long eventMicros = null;
  
  @GcPersistableField(columnName = "ntrl_lng_priv_dic_intrnl_id")
  private Long naturalLanguagePrivilegeDictionaryInternalId;

  @GcPersistableField(columnName = "ntrl_lng_unpriv_dic_intrnl_id")
  private Long naturalLanguageUnPrivilegeDictionaryInternalId;
  

  /**
   * version from db
   */
  @GcPersistableField(persist = GcPersist.dontPersist)
  private GrouperLifecycleEvent dbVersion;
  
  /**
   * store the internal id to use when the db access stores the object
   */
  @GcPersistableField(persist = GcPersist.dontPersist)
  private Long tempInternalIdOnDeck = null;

  /**
   * store the internal id to use when the db access stores the object
   * @return
   */
  public Long getTempInternalIdOnDeck() {
    return tempInternalIdOnDeck;
  }

  /**
   * store the internal id to use when the db access stores the object
   * @param tempInternalIdOnDeck
   */
  public void setTempInternalIdOnDeck(Long tempInternalIdOnDeck) {
    this.tempInternalIdOnDeck = tempInternalIdOnDeck;
  }

  
  public long getInternalId() {
    return internalId;
  }

  
  public void setInternalId(long internalId) {
    this.internalId = internalId;
  }
  
  
  
  public Long getGroupLifecycleEventConfigInternalId() {
    return groupLifecycleEventConfigInternalId;
  }

  
  public void setGroupLifecycleEventConfigInternalId(
      Long groupLifecycleEventConfigInternalId) {
    this.groupLifecycleEventConfigInternalId = groupLifecycleEventConfigInternalId;
  }

  
  public Long getMemberInternalId() {
    return memberInternalId;
  }

  
  public void setMemberInternalId(Long memberInternalId) {
    this.memberInternalId = memberInternalId;
  }

  
  public Long getEventMicros() {
    return eventMicros;
  }

  
  public void setEventMicros(Long eventMicros) {
    this.eventMicros = eventMicros;
  }

  
  public Long getNaturalLanguagePrivilegeDictionaryInternalId() {
    return naturalLanguagePrivilegeDictionaryInternalId;
  }

  
  public void setNaturalLanguagePrivilegeDictionaryInternalId(
      Long naturalLanguagePrivilegeDictionaryInternalId) {
    this.naturalLanguagePrivilegeDictionaryInternalId = naturalLanguagePrivilegeDictionaryInternalId;
  }

  
  public Long getNaturalLanguageUnPrivilegeDictionaryInternalId() {
    return naturalLanguageUnPrivilegeDictionaryInternalId;
  }

  
  public void setNaturalLanguageUnPrivilegeDictionaryInternalId(
      Long naturalLanguageUnPrivilegeDictionaryInternalId) {
    this.naturalLanguageUnPrivilegeDictionaryInternalId = naturalLanguageUnPrivilegeDictionaryInternalId;
  }

  /**
   * 
   */
  @Override
  public boolean gcSqlAssignNewPrimaryKeyForInsert() {
    if (this.internalId != -1) {
      return false;
    }
    if (this.tempInternalIdOnDeck != null) {
      this.internalId = this.tempInternalIdOnDeck;
    } else {
      this.internalId = TableIndex.reserveId(TableIndexType.lifecycleEvent);
    }
    return true;
  }


  //########## END GENERATED BY GcDbVersionableGenerate.java ###########
  
  /**
   * deep clone the fields in this object
   */
  @Override
  public GrouperLifecycleEvent clone() {
  
    GrouperLifecycleEvent grouperLifecycleEvent = new GrouperLifecycleEvent();
  
    grouperLifecycleEvent.groupLifecycleEventConfigInternalId = this.groupLifecycleEventConfigInternalId;
    grouperLifecycleEvent.memberInternalId = this.memberInternalId;
    grouperLifecycleEvent.internalId = this.internalId;
    grouperLifecycleEvent.eventMicros = this.eventMicros;
    grouperLifecycleEvent.naturalLanguageUnPrivilegeDictionaryInternalId = this.naturalLanguageUnPrivilegeDictionaryInternalId;
    grouperLifecycleEvent.naturalLanguagePrivilegeDictionaryInternalId = this.naturalLanguagePrivilegeDictionaryInternalId;
  
    return grouperLifecycleEvent;
  }


  /**
   * db version
   */
  @Override
  public void dbVersionDelete() {
    this.dbVersion = null;
  }


  /**
   * if we need to update this object
   * @return if needs to update this object
   */
  @Override
  public boolean dbVersionDifferent() {
    return !this.equalsDeep(this.dbVersion);
  }


  /**
   * take a snapshot of the data since this is what is in the db
   */
  @Override
  public void dbVersionReset() {
    //lets get the state from the db so we know what has changed
    this.dbVersion = this.clone();
  }


  /**
   *
   */
  public boolean equalsDeep(Object obj) {
    if (this==obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (!(obj instanceof GrouperLifecycleEvent)) {
      return false;
    }
    GrouperLifecycleEvent other = (GrouperLifecycleEvent) obj;
  
    return new EqualsBuilder()
      //dbVersion  DONT EQUALS
      .append(this.groupLifecycleEventConfigInternalId, other.groupLifecycleEventConfigInternalId)
      .append(this.internalId, other.internalId)
      .append(this.memberInternalId, other.memberInternalId)
      .append(this.eventMicros, other.eventMicros)
      .append(this.naturalLanguageUnPrivilegeDictionaryInternalId, other.naturalLanguageUnPrivilegeDictionaryInternalId)
      .append(this.naturalLanguagePrivilegeDictionaryInternalId, other.naturalLanguagePrivilegeDictionaryInternalId)
        .isEquals();
  
  }


  /**
   * 
   */
  @Override
  public String toString() {
    return GrouperClientUtils.toStringReflection(this, null);
  }


  /**
   * delete all data if table is here
   */
  public static void reset() {
    
    new GcDbAccess().connectionName("grouper").sql("delete from " + GcPersistableHelper.tableName(GrouperLifecycleEvent.class)).executeSql();
  }

  public GrouperLifecycleEvent getDbVersion() {
    return this.dbVersion;
  }
  
}
