#!/bin/sh
#
# Startup script for the Tomcat Server
#
# chkconfig: - 86 14
# description: Tomcat
# processname:
# pidfile:
# config:
# Tomcat
# description: Starts and stops the Tomcat
# See how we were called.

export CATALINA_BASE="/home/test9/tomcat"
export TOMCAT_NAME="tomcat_test9"
export JAVA_HOME="/opt/javas/java_test9"
export JAVA_OPTS="-server -Xms50M -Xmx240M -XX:MaxPermSize=120M"

export TOMCAT_HOME="/opt/tomcat6base"
export CATALINA_HOME="/opt/tomcat6base"

export TOMCAT_USER="test9"

source /etc/init.d/tomcat_helper $1

