CREATE TABLE SECUREUSERDATA_MEMBERSHIPS
(
  ID               VARCHAR2(32 CHAR)            NOT NULL,
  PERSONID         VARCHAR2(32 CHAR)            NOT NULL,
  GROUP_EXTENSION  VARCHAR2(32 CHAR)            NOT NULL
);

COMMENT ON TABLE SECUREUSERDATA_MEMBERSHIPS IS 'holds memberships for row level security';

COMMENT ON COLUMN SECUREUSERDATA_MEMBERSHIPS.ID IS 'uuid of row';

COMMENT ON COLUMN SECUREUSERDATA_MEMBERSHIPS.PERSONID IS 'personid of person in group';

COMMENT ON COLUMN SECUREUSERDATA_MEMBERSHIPS.GROUP_EXTENSION IS 'name (without folder name) of group, e.g. all, fgacFacultyAndStaff, fgacStudents';



CREATE UNIQUE INDEX SECUREUSERDATA_MEMBERSHIPS_PK ON SECUREUSERDATA_MEMBERSHIPS
(ID);


ALTER TABLE SECUREUSERDATA_MEMBERSHIPS ADD (
  CONSTRAINT SECUREUSERDATA_MEMBERSHIPS_PK
  PRIMARY KEY
  (ID)
  USING INDEX SECUREUSERDATA_MEMBERSHIPS_PK);

GRANT SELECT ON SECUREUSERDATA_MEMBERSHIPS TO FASTDEV2;

GRANT SELECT ON SECUREUSERDATA_MEMBERSHIPS TO FASTDEV3;
