CREATE TABLE SECUREUSERDATA_ROW_PERMISS
(
  ID               VARCHAR2(32 CHAR)            NOT NULL,
  GROUP_EXTENSION  VARCHAR2(32 CHAR)            NOT NULL,
  SCHEMA_NAME      VARCHAR2(32 CHAR)            NOT NULL,
  ACTION           VARCHAR2(32 BYTE)            NOT NULL
);

COMMENT ON TABLE SECUREUSERDATA_ROW_PERMISS IS 'holds row permissions per schema';

COMMENT ON COLUMN SECUREUSERDATA_ROW_PERMISS.ID IS 'uuid for row';

COMMENT ON COLUMN SECUREUSERDATA_ROW_PERMISS.GROUP_EXTENSION IS 'name (without folder name) of group, e.g. all, fgacFacultyAndStaff, fgacStudents';

COMMENT ON COLUMN SECUREUSERDATA_ROW_PERMISS.SCHEMA_NAME IS 'schema with permission';

COMMENT ON COLUMN SECUREUSERDATA_ROW_PERMISS.ACTION IS 'read or write';



CREATE UNIQUE INDEX SECUREUSERDATA_ROW_PERMISS_PK ON SECUREUSERDATA_ROW_PERMISS
(ID);


CREATE INDEX SUD_ROW_PERMISS_GROUP_IDX ON SECUREUSERDATA_ROW_PERMISS
(GROUP_EXTENSION);


CREATE INDEX SUD_ROW_PERMISS_SCHEMA_IDX ON SECUREUSERDATA_ROW_PERMISS
(SCHEMA_NAME);


ALTER TABLE SECUREUSERDATA_ROW_PERMISS ADD (
  CONSTRAINT SECUREUSERDATA_ROW_PERMISS_PK
  PRIMARY KEY
  (ID)
  USING INDEX SECUREUSERDATA_ROW_PERMISS_PK);

GRANT SELECT ON SECUREUSERDATA_ROW_PERMISS TO FASTDEV1;

GRANT SELECT ON SECUREUSERDATA_ROW_PERMISS TO FASTDEV3;
