package edu.internet2.middleware.grouper.dataField;

import edu.internet2.middleware.grouper.tableIndex.TableIndex;
import edu.internet2.middleware.grouper.tableIndex.TableIndexType;
import edu.internet2.middleware.grouperClient.jdbc.GcDbVersionable;
import edu.internet2.middleware.grouperClient.jdbc.GcPersist;
import edu.internet2.middleware.grouperClient.jdbc.GcPersistableClass;
import edu.internet2.middleware.grouperClient.jdbc.GcPersistableField;
import edu.internet2.middleware.grouperClient.jdbc.GcSqlAssignPrimaryKey;
import edu.internet2.middleware.grouperClient.util.GrouperClientUtils;
import org.apache.commons.lang3.builder.EqualsBuilder;

/**
 *
 */
@GcPersistableClass(tableName="grouper_data_field_assign_hst", defaultFieldPersist=GcPersist.doPersist)
public class GrouperDataFieldAssignHst implements GcSqlAssignPrimaryKey, GcDbVersionable {

  private long dataFieldInternalId = -1;

  private long memberInternalId = -1;

  @GcPersistableField(primaryKey=true, primaryKeyManuallyAssigned=true)
  private long internalId = -1;
  
  private Long valueInteger;

  private Long valueDictionaryInternalId;
  
  private Long startTime;
  
  private Long endTime;

  /**
   * version from db
   */
  @GcPersistableField(persist = GcPersist.dontPersist)
  private GrouperDataFieldAssignHst dbVersion;


  /**
   * store the internal id to use when the db access stores the object
   */
  @GcPersistableField(persist = GcPersist.dontPersist)
  private Long tempInternalIdOnDeck = null;

  /**
   * store the internal id to use when the db access stores the object
   * @return
   */
  public Long getTempInternalIdOnDeck() {
    return tempInternalIdOnDeck;
  }

  /**
   * store the internal id to use when the db access stores the object
   * @param tempInternalIdOnDeck
   */
  public void setTempInternalIdOnDeck(Long tempInternalIdOnDeck) {
    this.tempInternalIdOnDeck = tempInternalIdOnDeck;
  }

  public long getInternalId() {
    return internalId;
  }

  
  public void setInternalId(long internalId) {
    this.internalId = internalId;
  }
  
  public long getDataFieldInternalId() {
    return dataFieldInternalId;
  }


  
  public void setDataFieldInternalId(long dataFieldInternalId) {
    this.dataFieldInternalId = dataFieldInternalId;
  }


  
  public long getMemberInternalId() {
    return memberInternalId;
  }


  
  public void setMemberInternalId(long memberInternalId) {
    this.memberInternalId = memberInternalId;
  }


  
  public Long getValueInteger() {
    return valueInteger;
  }


  
  public void setValueInteger(Long valueInteger) {
    this.valueInteger = valueInteger;
  }


  
  public Long getValueDictionaryInternalId() {
    return valueDictionaryInternalId;
  }


  
  public void setValueDictionaryInternalId(Long valueDictionaryInternalId) {
    this.valueDictionaryInternalId = valueDictionaryInternalId;
  }
  
  

  
  public Long getStartTime() {
    return startTime;
  }


  
  public void setStartTime(Long startTime) {
    this.startTime = startTime;
  }


  
  public Long getEndTime() {
    return endTime;
  }


  
  public void setEndTime(Long endTime) {
    this.endTime = endTime;
  }


  /**
   * 
   */
  @Override
  public boolean gcSqlAssignNewPrimaryKeyForInsert() {
    if (this.internalId != -1) {
      return false;
    }
    if (this.tempInternalIdOnDeck != null) {
      this.internalId = this.tempInternalIdOnDeck;
    } else {

      this.internalId = TableIndex.reserveId(TableIndexType.dataFieldAssignHst);
    }
    return true;
  }


  //########## END GENERATED BY GcDbVersionableGenerate.java ###########
  
  /**
   * deep clone the fields in this object
   */
  @Override
  public GrouperDataFieldAssignHst clone() {
  
    GrouperDataFieldAssignHst grouperDataFieldAssign = new GrouperDataFieldAssignHst();
  
    //dbVersion  DONT CLONE
  
    grouperDataFieldAssign.startTime = this.startTime;
    grouperDataFieldAssign.endTime = this.endTime;
    grouperDataFieldAssign.dataFieldInternalId = this.dataFieldInternalId;
    grouperDataFieldAssign.internalId = this.internalId;
    grouperDataFieldAssign.valueInteger = this.valueInteger;
    grouperDataFieldAssign.memberInternalId = this.memberInternalId;
    grouperDataFieldAssign.valueDictionaryInternalId = this.valueDictionaryInternalId;
  
    return grouperDataFieldAssign;
  }


  /**
   * db version
   */
  @Override
  public void dbVersionDelete() {
    this.dbVersion = null;
  }


  /**
   * if we need to update this object
   * @return if needs to update this object
   */
  @Override
  public boolean dbVersionDifferent() {
    return !this.equalsDeep(this.dbVersion);
  }


  /**
   * take a snapshot of the data since this is what is in the db
   */
  @Override
  public void dbVersionReset() {
    //lets get the state from the db so we know what has changed
    this.dbVersion = this.clone();
  }


  /**
   *
   */
  public boolean equalsDeep(Object obj) {
    if (this==obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (!(obj instanceof GrouperDataFieldAssignHst)) {
      return false;
    }
    GrouperDataFieldAssignHst other = (GrouperDataFieldAssignHst) obj;
  
    return new EqualsBuilder()
  
      //dbVersion  DONT EQUALS
      .append(this.startTime, other.startTime)
      .append(this.endTime, other.endTime)
      .append(this.dataFieldInternalId, other.dataFieldInternalId)
      .append(this.internalId, other.internalId)
      .append(this.memberInternalId, other.memberInternalId)
      .append(this.valueDictionaryInternalId, other.valueDictionaryInternalId)
      .append(this.valueInteger, other.valueInteger)
        .isEquals();
  
  }


  public void storePrepare() {

  }


  /**
   * 
   */
  @Override
  public String toString() {
    return GrouperClientUtils.toStringReflection(this, null);
  }

  public GrouperDataFieldAssignHst getDbVersion() {
    return this.dbVersion;
  }
}
