#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

ME="${BASH_SOURCE[0]}"
while [ -h "$ME" ]; do ME=$(readlink "$ME"); done

D="$( cd "$( dirname "${ME}" )" && pwd -P )"
. "$D/../functions.bash"

cd "$D"

# This is the base of all other versions
grouper-pspng-testing-config/buildit

# If we're trying to use the devel version (the default), then compile pspng
[ "${GROUPER_VERSION}:-devel}" = devel ] &&  grouper-pspng-devel/compile-for-docker-image

docker-compose build


VOLUMES_NEEDED=
for volume in db-data-template ldap-data-template ldap-config-template; do
    if ! docker volume inspect $volume >/dev/null 2>&1; then
      VOLUMES_NEEDED="$VOLUMES_NEEDED,$volume"
    fi
done

if [ -n "$VOLUMES_NEEDED" ]; then
  log_always "Building volume templates: $VOLUMES_NEEDED"
  ./create-data-templates
else
  log_always "Volume templates already exist"
fi
