#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

ME="${BASH_SOURCE[0]}"
while [ -h "$ME" ]; do ME=$(readlink "$ME"); done

D="$( cd "$( dirname "$ME}" )" && pwd -P )"
. "$D/../functions.bash"

cd "$D"

grouper-pspng-devel/compile-for-docker-image

docker-compose build
