delete from signet_category where subsystemID='testSubsystemId'
delete from signet_function_permission where subsystemID='testSubsystemId'
delete from signet_function where subsystemID='testSubsystemId'
delete from signet_permission_limit where subsystemID='testSubsystemId'
delete from signet_permission where subsystemID='testSubsystemId'
delete from signet_limit where subsystemID='testSubsystemId'
delete from signet_subsystem where subsystemID='testSubsystemId'
delete from signet_choice where choiceSetID like 'CHOICE_SET_%'
delete from signet_choiceSet where choiceSetID like 'CHOICE_SET_%'
delete from signet_Subject where subjectID like 'SUBJECT_%_ID'
delete from signet_tree where treeID = 'testTreeId'
delete from signet_treeNode where treeID = 'testTreeId'
delete from signet_treeNodeRelationship where treeID = 'testTreeId'
delete from signet_assignment where subsystemID='testSubsystemId'
delete from signet_assignmentLimit where limitSubsystemID='testSubsystemId'