/* Generated By:JJTree: Do not edit this line. ASTDivNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.internet2.middleware.tierApiAuthzClientExt.org.apache.commons.jexl2.parser;

public
class ASTDivNode extends JexlNode {
  public ASTDivNode(int id) {
    super(id);
  }

  public ASTDivNode(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a43a3e28e72018c032291cb6792d1f4a (do not edit this line) */
