/* Generated By:JJTree: Do not edit this line. ASTUnaryMinusNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.internet2.middleware.tierApiAuthzClientExt.org.apache.commons.jexl2.parser;

public
class ASTUnaryMinusNode extends JexlNode {
  public ASTUnaryMinusNode(int id) {
    super(id);
  }

  public ASTUnaryMinusNode(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d1dd8266d18ddb563be811152cbed4b7 (do not edit this line) */
