/**
 * Copyright 2012 Internet2
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package edu.internet2.middleware.grouperClientExt.org.apache.commons.jexl2.parser;

public interface ParserTreeConstants
{
  public int JJTJEXLSCRIPT = 0;
  public int JJTVOID = 1;
  public int JJTBLOCK = 2;
  public int JJTAMBIGUOUS = 3;
  public int JJTIFSTATEMENT = 4;
  public int JJTWHILESTATEMENT = 5;
  public int JJTFOREACHSTATEMENT = 6;
  public int JJTRETURNSTATEMENT = 7;
  public int JJTASSIGNMENT = 8;
  public int JJTVAR = 9;
  public int JJTREFERENCE = 10;
  public int JJTTERNARYNODE = 11;
  public int JJTORNODE = 12;
  public int JJTANDNODE = 13;
  public int JJTBITWISEORNODE = 14;
  public int JJTBITWISEXORNODE = 15;
  public int JJTBITWISEANDNODE = 16;
  public int JJTEQNODE = 17;
  public int JJTNENODE = 18;
  public int JJTLTNODE = 19;
  public int JJTGTNODE = 20;
  public int JJTLENODE = 21;
  public int JJTGENODE = 22;
  public int JJTERNODE = 23;
  public int JJTNRNODE = 24;
  public int JJTADDITIVENODE = 25;
  public int JJTADDITIVEOPERATOR = 26;
  public int JJTMULNODE = 27;
  public int JJTDIVNODE = 28;
  public int JJTMODNODE = 29;
  public int JJTUNARYMINUSNODE = 30;
  public int JJTBITWISECOMPLNODE = 31;
  public int JJTNOTNODE = 32;
  public int JJTIDENTIFIER = 33;
  public int JJTNULLLITERAL = 34;
  public int JJTTRUENODE = 35;
  public int JJTFALSENODE = 36;
  public int JJTNUMBERLITERAL = 37;
  public int JJTSTRINGLITERAL = 38;
  public int JJTARRAYLITERAL = 39;
  public int JJTMAPLITERAL = 40;
  public int JJTMAPENTRY = 41;
  public int JJTEMPTYFUNCTION = 42;
  public int JJTSIZEFUNCTION = 43;
  public int JJTFUNCTIONNODE = 44;
  public int JJTMETHODNODE = 45;
  public int JJTSIZEMETHOD = 46;
  public int JJTCONSTRUCTORNODE = 47;
  public int JJTARRAYACCESS = 48;
  public int JJTREFERENCEEXPRESSION = 49;


  public String[] jjtNodeName = {
    "JexlScript",
    "void",
    "Block",
    "Ambiguous",
    "IfStatement",
    "WhileStatement",
    "ForeachStatement",
    "ReturnStatement",
    "Assignment",
    "Var",
    "Reference",
    "TernaryNode",
    "OrNode",
    "AndNode",
    "BitwiseOrNode",
    "BitwiseXorNode",
    "BitwiseAndNode",
    "EQNode",
    "NENode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "ERNode",
    "NRNode",
    "AdditiveNode",
    "AdditiveOperator",
    "MulNode",
    "DivNode",
    "ModNode",
    "UnaryMinusNode",
    "BitwiseComplNode",
    "NotNode",
    "Identifier",
    "NullLiteral",
    "TrueNode",
    "FalseNode",
    "NumberLiteral",
    "StringLiteral",
    "ArrayLiteral",
    "MapLiteral",
    "MapEntry",
    "EmptyFunction",
    "SizeFunction",
    "FunctionNode",
    "MethodNode",
    "SizeMethod",
    "ConstructorNode",
    "ArrayAccess",
    "ReferenceExpression",
  };
}
/* JavaCC - OriginalChecksum=ec2892c8a8789aa5a1927124df8511e0 (do not edit this line) */
