/* Generated By:JJTree: Do not edit this line. ASTERNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.internet2.middleware.authzStandardApiClientExt.org.apache.commons.jexl2.parser;

public
class ASTERNode extends JexlNode {
  public ASTERNode(int id) {
    super(id);
  }

  public ASTERNode(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=709c0505ad64718faf3d8c72bb5210f8 (do not edit this line) */
