/* Generated By:JJTree: Do not edit this line. ASTTernaryNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.internet2.middleware.authzStandardApiClientExt.org.apache.commons.jexl2.parser;

public
class ASTTernaryNode extends JexlNode {
  public ASTTernaryNode(int id) {
    super(id);
  }

  public ASTTernaryNode(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6ad3fd7dfb517b3c94ed286d3462b104 (do not edit this line) */
