#!/bin/bash

PATH=/container-files/bin:$PATH

. functions.bash
tempfile_into_T

if myldapsearch -b dc=example,dc=edu -s base dn >$T 2>&1; then
  echo "Ldap server is ready"
  exit 0
fi

ERROR_INTERVAL=10
LAST_ERROR_EPOCH=$(( $(date +%s) - ERROR_INTERVAL ))

echo -n Waiting for ldap server...
while ! myldapsearch -b dc=example,dc=edu -s base dn >$T 2>&1;
do
  NOW=$(date +%s)
  if [ $(( NOW - LAST_ERROR_EPOCH )) -ge $ERROR_INTERVAL ]; then
    echo ""
    cat $T
    LAST_ERROR_EPOCH=$NOW
  else
    echo -n .
  fi
  sleep 0.5
done

echo ready
