#!/bin/bash

D="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
. "$D/functions.bash"
. "$D/shflags"

DEFINE_string group_name "" "Full path to group"

# parse the command-line
FLAGS "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

[ -z "$FLAGS_group_name" ] && fail "--group_name must be specified"

set -o errexit
set -o pipefail
set -o nounset

$GSH <<EOF
gs = GrouperSession.startRootSession();
delGroup("$FLAGS_group_name")

EOF
