#!/bin/bash

D="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
. "$D/functions.bash"
. "$D/shflags"

DEFINE_string subject "agasper" "Subject to look up, default: agasper"

# parse the command-line
FLAGS "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

set -o errexit
set -o pipefail
set -o nounset

await-mysql-server
await-ldap-server

tempfile_into_T
cat >$T <<EOF
gs = GrouperSession.startRootSession();
subject = findSubject("$FLAGS_subject");
EOF

echo Running GSH with:
cat $T
echo ===

$GSH < $T 2>&1 | tee $T.out

ERRORS=$(grep_ ERROR $T.out)

if [ -z "$ERRORS" ]; then
  echo Subject source is working
  exit 0
else
  echo Subject source failure: $ERRORS
  exit 1
fi

 
