define('grouper/nls/grouperDojo_zh-tw',{
'dijit/form/nls/ComboBox':{"previousMessage":"前一個選擇項","nextMessage":"其他選擇項"}
,
'dijit/nls/loading':{"loadingState":"載入中...","errorState":"抱歉，發生錯誤"}
,
'dijit/form/nls/validate':{"rangeMessage":"此值超出範圍。","invalidMessage":"輸入的值無效。","missingMessage":"必須提供此值。"}
,
'dijit/nls/common':{"buttonOk":"確定","buttonCancel":"取消","buttonSave":"儲存","itemClose":"關閉"}
});