# This particular hook test can't be selectively enabled, because the attribute is
# only created when grouper.enable.rule.cannotAddSelfToGroup is true at startup
junit.test.membershipCannotAddSelfToGroupHook = false

# Needs a value now (GRP-6421 checks value != prod)
grouper.env.name=testEnv

#####################################
## Testing settings
#####################################

junit.test.loader = true

junit.test.tableSync = true

# The ddl tests don't currently recover all the tables and affect further tests
junit.test.ddl = false

junit.test.sqlProvisioning = false

junit.test.gsh = false

junit.test.stress = false

junit.test.clientConfig = false

junit.test.tomcat =

junit.test.externalSubjects = false

junit.test.groupSync = false

junit.test.groupSync.url = https://grouperdemo.internet2.edu/grouper-ws_v2_0_0/servicesRest

junit.test.groupSync.user = remoteUser

junit.test.groupSync.password = R:/pass/grouperDemoRemoteUser.pass

junit.test.groupSync.folder = test2:whateverFolder

junit.test.groupSync.pushAddExternalSubjectIfNotExist = true

junit.test.groupSync.createRemoteFolderIfNotExist = true

junit.test.groupSync.remoteSourceId = grouperExternal

junit.test.groupSync.remoteReadSubjectId = identifier

junit.test.groupSync.remoteWriteSubjectId = identifier

junit.test.ldap.source = false

junit.test.ldap.dinkel = false

junit.test.databaseCache = false

junit.test.tomcat.startCommand =

junit.test.tomcat.stopCommand =

junit.test.tomcat.port = 8080

junit.test.tomcat.ipAddress = 0.0.0.0

junit.test.tomcat.domainName = localhost

junit.test.tomcat.waitForProcessReturn =

junit.test.tomcat.ssl =

junit.test.ldapSleepMillisOnTestStartup =

junit.test.docker.command =
