/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package edu.internet2.middleware.authzStandardApiServerExt.org.apache.commons.jexl2.parser;

public interface ParserTreeConstants
{
  public int JJTJEXLSCRIPT = 0;
  public int JJTVOID = 1;
  public int JJTBLOCK = 2;
  public int JJTAMBIGUOUS = 3;
  public int JJTIFSTATEMENT = 4;
  public int JJTWHILESTATEMENT = 5;
  public int JJTFOREACHSTATEMENT = 6;
  public int JJTASSIGNMENT = 7;
  public int JJTTERNARYNODE = 8;
  public int JJTORNODE = 9;
  public int JJTANDNODE = 10;
  public int JJTBITWISEORNODE = 11;
  public int JJTBITWISEXORNODE = 12;
  public int JJTBITWISEANDNODE = 13;
  public int JJTEQNODE = 14;
  public int JJTNENODE = 15;
  public int JJTLTNODE = 16;
  public int JJTGTNODE = 17;
  public int JJTLENODE = 18;
  public int JJTGENODE = 19;
  public int JJTERNODE = 20;
  public int JJTNRNODE = 21;
  public int JJTADDITIVENODE = 22;
  public int JJTADDITIVEOPERATOR = 23;
  public int JJTMULNODE = 24;
  public int JJTDIVNODE = 25;
  public int JJTMODNODE = 26;
  public int JJTUNARYMINUSNODE = 27;
  public int JJTBITWISECOMPLNODE = 28;
  public int JJTNOTNODE = 29;
  public int JJTIDENTIFIER = 30;
  public int JJTNULLLITERAL = 31;
  public int JJTTRUENODE = 32;
  public int JJTFALSENODE = 33;
  public int JJTINTEGERLITERAL = 34;
  public int JJTFLOATLITERAL = 35;
  public int JJTSTRINGLITERAL = 36;
  public int JJTARRAYLITERAL = 37;
  public int JJTMAPLITERAL = 38;
  public int JJTMAPENTRY = 39;
  public int JJTEMPTYFUNCTION = 40;
  public int JJTSIZEFUNCTION = 41;
  public int JJTFUNCTIONNODE = 42;
  public int JJTMETHODNODE = 43;
  public int JJTSIZEMETHOD = 44;
  public int JJTCONSTRUCTORNODE = 45;
  public int JJTARRAYACCESS = 46;
  public int JJTREFERENCE = 47;


  public String[] jjtNodeName = {
    "JexlScript",
    "void",
    "Block",
    "Ambiguous",
    "IfStatement",
    "WhileStatement",
    "ForeachStatement",
    "Assignment",
    "TernaryNode",
    "OrNode",
    "AndNode",
    "BitwiseOrNode",
    "BitwiseXorNode",
    "BitwiseAndNode",
    "EQNode",
    "NENode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "ERNode",
    "NRNode",
    "AdditiveNode",
    "AdditiveOperator",
    "MulNode",
    "DivNode",
    "ModNode",
    "UnaryMinusNode",
    "BitwiseComplNode",
    "NotNode",
    "Identifier",
    "NullLiteral",
    "TrueNode",
    "FalseNode",
    "IntegerLiteral",
    "FloatLiteral",
    "StringLiteral",
    "ArrayLiteral",
    "MapLiteral",
    "MapEntry",
    "EmptyFunction",
    "SizeFunction",
    "FunctionNode",
    "MethodNode",
    "SizeMethod",
    "ConstructorNode",
    "ArrayAccess",
    "Reference",
  };
}
/* JavaCC - OriginalChecksum=d011bbb10fdfcc1a634fb5a90e30131e (do not edit this line) */
