otherJob.tierInstrumentationDaemon.quartzCron = 0 0 2 * * ? 2099

ldap.ldap1.url = ldap://ldap:389
ldap.ldap1.user = cn=admin,dc=example,dc=edu
ldap.ldap1.pass = secret
ldap.ldap1.tls = false
ldap.ldap1.uiTestSearchDn = dc=example,dc=edu
ldap.ldap1.uiTestSearchScope = SUBTREE_SCOPE
ldap.ldap1.uiTestFilter = uid=banderson
ldap.ldap1.uiTestAttributeName = employeeNumber
ldap.ldap1.uiTestExpectedValue = 800001147
