subjectApi.source.ldap.adapterClass = edu.internet2.middleware.grouper.subj.GrouperLdapSourceAdapter2_5
subjectApi.source.ldap.id = eduLDAP
subjectApi.source.ldap.name = LDAP users
subjectApi.source.ldap.types = person
subjectApi.source.ldap.param.ldapServerId.value = ldap1
subjectApi.source.ldap.numberOfAttributes = 9
subjectApi.source.ldap.attribute.0.name = uid
subjectApi.source.ldap.attribute.0.subjectIdentifier = true
subjectApi.source.ldap.attribute.0.translationType = sourceAttributeSameAsSubjectAttribute
subjectApi.source.ldap.attribute.0.formatToLowerCase = false
subjectApi.source.ldap.attribute.1.name = cn
subjectApi.source.ldap.attribute.1.translationType = sourceAttributeSameAsSubjectAttribute
subjectApi.source.ldap.attribute.1.formatToLowerCase = false
subjectApi.source.ldap.attribute.2.name = mail
subjectApi.source.ldap.attribute.2.translationType = sourceAttributeSameAsSubjectAttribute
subjectApi.source.ldap.attribute.2.formatToLowerCase = false
subjectApi.source.ldap.attribute.3.name = givenName
subjectApi.source.ldap.attribute.3.translationType = sourceAttributeSameAsSubjectAttribute
subjectApi.source.ldap.attribute.3.formatToLowerCase = false
subjectApi.source.ldap.attribute.4.name = sn
subjectApi.source.ldap.attribute.4.translationType = sourceAttributeSameAsSubjectAttribute
subjectApi.source.ldap.attribute.4.formatToLowerCase = false
subjectApi.source.ldap.attribute.5.name = employeeNumber
subjectApi.source.ldap.attribute.5.translationType = sourceAttributeSameAsSubjectAttribute
subjectApi.source.ldap.attribute.5.formatToLowerCase = false
subjectApi.source.ldap.attribute.6.name = searchAttribute0
subjectApi.source.ldap.attribute.6.translationType = translation
subjectApi.source.ldap.attribute.6.translation = ${subject_attribute__employeenumber + '|' + subject_attribute__uid + '|' + subject_attribute__cn}
subjectApi.source.ldap.attribute.6.internal = true
subjectApi.source.ldap.attribute.6.formatToLowerCase = true
subjectApi.source.ldap.attribute.7.name = description
subjectApi.source.ldap.attribute.7.formatToLowerCase = false
subjectApi.source.ldap.attribute.7.translation = ${source_attribute__cn + ' (' + source_attribute__uid + ')'}
subjectApi.source.ldap.attribute.7.translationType = translation
subjectApi.source.ldap.attribute.8.name = sortAttribute0
subjectApi.source.ldap.attribute.8.formatToLowerCase = true
subjectApi.source.ldap.attribute.8.translation = ${subject_attribute__sn + ',' + subject_attribute__givenname}
subjectApi.source.ldap.attribute.8.translationType = translation
subjectApi.source.ldap.attribute.8.internal = true
subjectApi.source.ldap.search.search.param.filter.value = (&(|(uid=%TERM%*)(employeeNumber=%TERM%*)(cn=*%TERM%*))(objectclass=eduPerson))
subjectApi.source.ldap.param.subjectIdentifierAttribute0.value = uid
subjectApi.source.ldap.param.subjectIdentifierAttribute1.value = mail
subjectApi.source.ldap.param.SubjectID_AttributeType.value = employeeNumber
subjectApi.source.ldap.param.Name_AttributeType.value = cn
subjectApi.source.ldap.param.Description_AttributeType.value = description
subjectApi.source.ldap.param.emailAttributeName.value = mail
subjectApi.source.ldap.param.netId.value = uid
subjectApi.source.ldap.searchAttributeCount = 1
subjectApi.source.ldap.searchAttribute.0.attributeName = searchAttribute0
subjectApi.source.ldap.sortAttributeCount = 1
subjectApi.source.ldap.sortAttribute.0.attributeName = sortAttribute0
subjectApi.source.ldap.search.searchSubject.param.base.value = ou=People,dc=example,dc=edu
subjectApi.source.ldap.search.searchSubject.param.filter.value = (&(employeeNumber=%TERM%)(objectclass=eduPerson))
subjectApi.source.ldap.search.searchSubject.param.scope.value = SUBTREE_SCOPE
subjectApi.source.ldap.search.searchSubjectByIdentifier.param.filter.value = (&(uid=%TERM%)(objectclass=eduPerson))
subjectApi.source.ldap.param.stringToFindOnCheckConfig.value = Bob Anderson
subjectApi.source.ldap.param.subjectIdToFindOnCheckConfig.value = 800001147
subjectApi.source.ldap.param.subjectIdentifierToFindOnCheckConfig.value = banderson
subjectApi.source.ldap.param.findSubjectByStringOnCheckConfig.value = true
