#!/bin/sh
# $Id: gsh,v 1.1 2006-05-30 19:40:51 blair Exp $

GROUPER_HOME=${HOME}/grouper@uchicago
CDG_HOME=${GROUPER_HOME}/contrib/cdg

CP=${CLASSPATH}
CP=${CP}:${GROUPER_HOME}/build/grouper
CP=${CP}:${GROUPER_HOME}/conf
for f in ${GROUPER_HOME}/lib/*.jar; do CP=${CP}:${f}; done
CP=${CP}:${CDG_HOME}/build/cdg
for f in ${CDG_HOME}/lib/*.jar; do CP=${CP}:${f}; done

java -classpath ${CP} com.devclue.grouper.shell.GrouperShell "$@"
exit $?

