/*
 * Copyright (C) 2004-2005 University Corporation for Advanced Internet Development, Inc.
 * Copyright (C) 2004-2005 The University Of Chicago
 * All Rights Reserved. 
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of the University of Chicago nor the names
 *    of its contributors nor the University Corporation for Advanced
 *   Internet Development, Inc. may be used to endorse or promote
 *   products derived from this software without explicit prior
 *   written permission.
 *
 * You are under no obligation whatsoever to provide any enhancements
 * to the University of Chicago, its contributors, or the University
 * Corporation for Advanced Internet Development, Inc.  If you choose
 * to provide your enhancements, or if you choose to otherwise publish
 * or distribute your enhancements, in source code form without
 * contemporaneously requiring end users to enter into a separate
 * written license agreement for such enhancements, then you thereby
 * grant the University of Chicago, its contributors, and the University
 * Corporation for Advanced Internet Development, Inc. a non-exclusive,
 * royalty-free, perpetual license to install, use, modify, prepare
 * derivative works, incorporate into the software or other computer
 * software, distribute, and sublicense your enhancements or derivative
 * works thereof, in binary and source code form.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND WITH ALL FAULTS.  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT ARE DISCLAIMED AND the
 * entire risk of satisfactory quality, performance, accuracy, and effort
 * is with LICENSEE. IN NO EVENT SHALL THE COPYRIGHT OWNER, CONTRIBUTORS,
 * OR THE UNIVERSITY CORPORATION FOR ADVANCED INTERNET DEVELOPMENT, INC.
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OR DISTRIBUTION OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * This class was generated by [Kodekopelli](http://www.kodekopelli.org/)
 */

package test.edu.internet2.middleware.grouper;

import  edu.internet2.middleware.grouper.*;
import  edu.internet2.middleware.subject.*;
import  edu.internet2.middleware.subject.provider.*;
import  java.io.*;
import  java.util.*;
import  junit.framework.*;

public class TestBug426 extends TestCase {

  public TestBug426(String name) {
    super(name);
  }

  private GrouperSession nrs, s;

protected void setUp () {
    DB db = new DB();
    db.emptyTables();
    db.stop();
    s = Constants.createSession();
    //Constants.createStems(s);
    Constants.createMembers(s);
    nrs = Constants.createSession(Constants.mem0I, Constants.mem0T);
  }

  protected void tearDown () {
    nrs.stop();
    s.stop();
  }


  /*
   * TESTS
   */

  public void testBug426Grant() {
    Assert.assertNotNull("s",   s);
    Assert.assertNotNull("nrs", nrs);
    // root: create ns0
    GrouperStem ns0 = GrouperStem.create(
      s, Constants.ns0s, Constants.ns0e
    );
    Assert.assertNotNull("ns0", ns0);
    // root: grant ns0/m0/STEM
    Assert.assertTrue(
      "root: grant ns0/m0/STEM",
      s.naming().grant(
        s, ns0, Constants.m0, Grouper.PRIV_STEM
      )
    );
    Assert.assertTrue(
      "ns0/m0/STEM",
      s.naming().has(s, ns0, Constants.m0, Grouper.PRIV_STEM)
    );
    // m0: create ns1
    GrouperStem ns1 = GrouperStem.create(
      nrs, Constants.ns1s, Constants.ns1e
    );
    Assert.assertNotNull("ns1", ns1);
    // m0: grant ns0/m0/CREATE
    Assert.assertTrue(
      "m0: grant ns0/m0/CREATE",
      nrs.naming().grant(
        nrs, ns0, Constants.m0, Grouper.PRIV_CREATE
      )
    );
    Assert.assertTrue(
      "ns0/m0/CREATE",
      nrs.naming().has(nrs, ns0, Constants.m0, Grouper.PRIV_CREATE)
    );
  }

  public void testBug426Revoke() {
    Assert.assertNotNull("s",   s);
    Assert.assertNotNull("nrs", nrs);
    // root: create ns0
    GrouperStem ns0 = GrouperStem.create(
      s, Constants.ns0s, Constants.ns0e
    );
    Assert.assertNotNull("ns0", ns0);
    // root: grant ns0/m0/STEM
    Assert.assertTrue(
      "root: grant ns0/m0/STEM",
      s.naming().grant(
        s, ns0, Constants.m0, Grouper.PRIV_STEM
      )
    );
    Assert.assertTrue(
      "ns0/m0/STEM",
      s.naming().has(s, ns0, Constants.m0, Grouper.PRIV_STEM)
    );
    // m0: create ns1
    GrouperStem ns1 = GrouperStem.create(
      nrs, Constants.ns1s, Constants.ns1e
    );
    Assert.assertNotNull("ns1", ns1);
    // m0: grant ns0/m0/CREATE
    Assert.assertTrue(
      "m0: grant ns0/m0/CREATE",
      nrs.naming().grant(
        nrs, ns0, Constants.m0, Grouper.PRIV_CREATE
      )
    );
    Assert.assertTrue(
      "ns0/m0/CREATE",
      nrs.naming().has(nrs, ns0, Constants.m0, Grouper.PRIV_CREATE)
    );
    // m0: revoke ns0/m0/CREATE
    Assert.assertTrue(
      "m0: revoke ns0/m0/CREATE",
      nrs.naming().revoke(
        nrs, ns0, Constants.m0, Grouper.PRIV_CREATE
      )
    );
    Assert.assertFalse(
      "!ns0/m0/CREATE",
      nrs.naming().has(nrs, ns0, Constants.m0, Grouper.PRIV_CREATE)
    );
  }

}

