/*
 * Copyright (C) 2004-2005 University Corporation for Advanced Internet Development, Inc.
 * Copyright (C) 2004-2005 The University Of Chicago
 * All Rights Reserved. 
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of the University of Chicago nor the names
 *    of its contributors nor the University Corporation for Advanced
 *   Internet Development, Inc. may be used to endorse or promote
 *   products derived from this software without explicit prior
 *   written permission.
 *
 * You are under no obligation whatsoever to provide any enhancements
 * to the University of Chicago, its contributors, or the University
 * Corporation for Advanced Internet Development, Inc.  If you choose
 * to provide your enhancements, or if you choose to otherwise publish
 * or distribute your enhancements, in source code form without
 * contemporaneously requiring end users to enter into a separate
 * written license agreement for such enhancements, then you thereby
 * grant the University of Chicago, its contributors, and the University
 * Corporation for Advanced Internet Development, Inc. a non-exclusive,
 * royalty-free, perpetual license to install, use, modify, prepare
 * derivative works, incorporate into the software or other computer
 * software, distribute, and sublicense your enhancements or derivative
 * works thereof, in binary and source code form.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND WITH ALL FAULTS.  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT ARE DISCLAIMED AND the
 * entire risk of satisfactory quality, performance, accuracy, and effort
 * is with LICENSEE. IN NO EVENT SHALL THE COPYRIGHT OWNER, CONTRIBUTORS,
 * OR THE UNIVERSITY CORPORATION FOR ADVANCED INTERNET DEVELOPMENT, INC.
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OR DISTRIBUTION OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * This class was generated by [Kodekopelli](http://www.kodekopelli.org/)
 */

package test.edu.internet2.middleware.grouper;

import  edu.internet2.middleware.grouper.*;
import  edu.internet2.middleware.subject.*;
import  edu.internet2.middleware.subject.provider.*;
import  java.io.*;
import  java.util.*;
import  junit.framework.*;

public class TestInstantiate extends TestCase {

  public TestInstantiate(String name) {
    super(name);
  }

  protected void setUp () {
    DB db = new DB();
    db.emptyTables();
    db.stop();
  }

  protected void tearDown () {
    // Nothing -- Yet
  }

  /*
   * TESTS
   */

  // Instantiate a GrouperAccessImpl instance
  public void testGrouperAccessImplInstantiate() {
    GrouperAccess obj = new GrouperAccessImpl();
    Assert.assertNotNull("Object is not null", obj);
    Assert.assertTrue(
      "Class is GrouperAccessImpl",
      obj.getClass().equals(GrouperAccessImpl.class)
    );
  }

  // Instantiate a GrouperAttribute instance
  public void testGrouperAttributeInstantiate() {
    GrouperAttribute obj = new GrouperAttribute();
    Assert.assertNotNull("Object is not null", obj);
    Assert.assertTrue(
      "Class is GrouperAttribute",
      obj.getClass().equals(GrouperAttribute.class)
    );
  }

  // Instantiate a GrouperException instance
  public void testGrouperExceptionInstantiate() {
    GrouperException obj = new GrouperException();
    Assert.assertNotNull("Object is not null", obj);
    Assert.assertTrue(
      "Class is GrouperException",
      obj.getClass().equals(GrouperException.class)
    );
  }

  // Instantiate a GrouperField instance
  public void testGrouperFieldInstantiate() {
    GrouperField obj = new GrouperField();
    Assert.assertNotNull("Object is not null", obj);
    Assert.assertTrue(
      "Class is GrouperField",
      obj.getClass().equals(GrouperField.class)
    );
  }

  // Instantiate a GrouperGroup instance
  public void testGrouperGroupInstantiate() {
    GrouperGroup obj = new GrouperGroup();
    Assert.assertNotNull("Object is not null", obj);
    Assert.assertTrue(
      "Class is GrouperGroup",
      obj.getClass().equals(GrouperGroup.class)
    );
  }

  // Instantiate a GrouperList instance
  public void testGrouperListInstantiate() {
    GrouperList obj = new GrouperList();
    Assert.assertNotNull("Object is not null", obj);
    Assert.assertTrue(
      "Class is GrouperList",
      obj.getClass().equals(GrouperList.class)
    );
  }

  // Instantiate a GrouperMember instance
  public void testGrouperMemberInstantiate() {
    GrouperMember obj = new GrouperMember();
    Assert.assertNotNull("Object is not null", obj);
    Assert.assertTrue(
      "Class is GrouperMember",
      obj.getClass().equals(GrouperMember.class)
    );
  }

  // Instantiate a GrouperNamingImpl instance
  public void testGrouperNamingImplInstantiate() {
    GrouperNaming obj = new GrouperNamingImpl();
    Assert.assertNotNull("Object is not null", obj);
    Assert.assertTrue(
      "Class is GrouperNamingImpl",
      obj.getClass().equals(GrouperNamingImpl.class)
    );
  }

  // Instantiate a GrouperSchema instance
  public void testGrouperSchemaInstantiate() {
    GrouperSchema obj = new GrouperSchema();
    Assert.assertNotNull("Object is not null", obj);
    Assert.assertTrue(
      "Class is GrouperSchema",
      obj.getClass().equals(GrouperSchema.class)
    );
  }

  // Instantiate a GrouperSession instance
  public void testGrouperSessionInstantiate() {
    GrouperSession obj = new GrouperSession();
    Assert.assertNotNull("Object is not null", obj);
    Assert.assertTrue(
      "Class is GrouperSession",
      obj.getClass().equals(GrouperSession.class)
    );
  }

  // Instantiate a GrouperStem instance
  public void testGrouperStemInstantiate() {
    GrouperStem obj = new GrouperStem();
    Assert.assertNotNull("Object is not null", obj);
    Assert.assertTrue(
      "Class is GrouperStem",
      obj.getClass().equals(GrouperStem.class)
    );
  }

  // Instantiate a GrouperType instance
  public void testGrouperTypeInstantiate() {
    GrouperType obj = new GrouperType();
    Assert.assertNotNull("Object is not null", obj);
    Assert.assertTrue(
      "Class is GrouperType",
      obj.getClass().equals(GrouperType.class)
    );
  }

  // Instantiate a GrouperTypeDef instance
  public void testGrouperTypeDefInstantiate() {
    GrouperTypeDef obj = new GrouperTypeDef();
    Assert.assertNotNull("Object is not null", obj);
    Assert.assertTrue(
      "Class is GrouperTypeDef",
      obj.getClass().equals(GrouperTypeDef.class)
    );
  }

  // Instantiate a MemberVia instance
  public void testMemberViaInstantiate() {
    MemberVia obj = new MemberVia();
    Assert.assertNotNull("Object is not null", obj);
    Assert.assertTrue(
      "Class is MemberVia",
      obj.getClass().equals(MemberVia.class)
    );
  }


}

